sudo: required
language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
cache:
  apt: true
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - libboost1.55-all-dev
notifications:
  email: false
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo unlink /usr/bin/g++; sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi
script:
  - cmake .; make; bin/mcmc_active -i dataset/karate.gml -r 1 -g 2 -p 10
  - cmake .; make; bin/mcmc_active -i dataset/polblogs_ud.gml -r 1 -g 2 -p 10

